{{- $svc := index .Values "erp-vacation" }}
apiVersion: v1
kind: Service
metadata:
  name: erp-vacation
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "modu-erp.labels" . | nindent 4 }}
    app.kubernetes.io/name: erp-vacation
spec:
  type: {{ $svc.service.type }}
  selector:
    app.kubernetes.io/name: erp-vacation
  ports:
    - port: {{ $svc.service.port }}
      targetPort: {{ $svc.service.port }}
      protocol: TCP
