{{- $svc := index .Values "erp-hr" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-hr
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "modu-erp.labels" . | nindent 4 }}
    app.kubernetes.io/name: erp-hr
spec:
  replicas: {{ $svc.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: erp-hr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: erp-hr
    spec:
      containers:
        - name: erp-hr
          image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
          imagePullPolicy: {{ $svc.image.pullPolicy }}
          ports:
            - containerPort: {{ $svc.service.port }}
          env:
            {{- include "modu-erp.commonEnv" . | nindent 12 }}
          resources:
            {{- toYaml $svc.resources | nindent 12 }}
